# Generated by Django 5.2.4 on 2025-08-07 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlanningStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_type', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('attractions', 'Attractions'), ('food', 'Food'), ('transport', 'Transport')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('selected_items', models.JSONField(blank=True, default=list)),
                ('ai_options', models.JSONField(blank=True, default=list)),
                ('stage_preferences', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_stages', to='travel.trip')),
            ],
            options={
                'ordering': ['trip', 'stage_type'],
                'unique_together': {('trip', 'stage_type')},
            },
        ),
    ]
