# Generated by Django 5.2.4 on 2025-08-07 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_tripplanningstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveItineraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField(default=1)),
                ('item_type', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('attraction', 'Attraction'), ('restaurant', 'Restaurant'), ('transport', 'Transport'), ('activity', 'Activity'), ('event', 'Event'), ('break', 'Break'), ('meal', 'Meal')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('planned_start_time', models.TimeField(blank=True, null=True)),
                ('planned_end_time', models.TimeField(blank=True, null=True)),
                ('actual_start_time', models.TimeField(blank=True, null=True)),
                ('actual_end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('completion_notes', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('booking_reference', models.CharField(blank=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_itinerary_items', to='travel.trip')),
            ],
            options={
                'ordering': ['trip', 'day_number', 'planned_start_time'],
                'unique_together': {('trip', 'day_number', 'title')},
            },
        ),
    ]
